[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43

build_flags =
  -D USER_SETUP_LOADED=1
  -D ESP32_PARALLEL=1
  
;   Driver de la pantalla
  -D ILI9341_DRIVER=1     
  
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320